CREATE TABLE IF NOT EXISTS `user_meta` (
    `id` VARCHAR(36) PRIMARY KEY NOT NULL,
    `userId` VARCHAR(36) NOT NULL UNIQUE,
    `bio` TEXT NULL,
    `graduationYear` VARCHAR(4) NULL,
    `courses` JSON NULL,
    `interests` JSON NULL,
    `clubs` JSON NULL,
    `lookingFor` JSON NULL,
    `createdAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE CASCADE
);
