DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS skills;

CREATE TABLE users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(50) NOT NULL, email VARCHAR(50) UNIQUE NOT NULL, profilePic VARCHAR(50), password VARCHAR(50) NOT NULL, role VARCHAR(50) NOT NULL, state VARCHAR(50) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE skills(id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name VARCHAR(50) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);